# Global settings
port = 873

# means no limit
max connections = 0

log file = /var/log/rsyncd.log

# Module definition
[klog]
    path = /mnt/klog1
    comment = kscale log directory
    refuse options = delete* force
    read only = no
    use chroot = no
    uid = data
    gid = datagroup
    incoming chmod = Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r
